In [2]:
import pandas as pd

def csvtotext(input_csv_file, output_text_file, encoding='utf-8'):
    df = pd.read_csv(input_csv_file)
    df = df.head(100)

    with open(output_text_file, 'w', encoding=encoding) as text_file:
        for index, row in df.iterrows():
            text_file.write(str(row.iloc[0]) + '\n')

input_csv_file = 'quotes.csv'
output_text_file = 'extracted.txt'

csvtotext(input_csv_file, output_text_file)


In [3]:
file_path = "extracted.txt"  # Update the file path if your file is in a different location

try:
    with open(file_path, 'r', encoding='utf-8') as file:
        data = file.read()
        print("File content successfully read and stored in a string.")

except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found.")

except Exception as e:
    print(f"An error occurred: {e}")


File content successfully read and stored in a string.


In [4]:
data

'I\'m selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can\'t handle me at my worst, then you sure as hell don\'t deserve me at my best.\nYou\'ve gotta dance like there\'s nobody watching,Love like you\'ll never be hurt,Sing like there\'s nobody listening,And live like it\'s heaven on earth.\nYou know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.\nA friend is someone who knows all about you and still loves you.\nDarkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.\nWe accept the love we think we deserve.\nOnly once in your life, I truly believe, you find someone who can completely turn your world around. You tell them things that you’ve never shared with another soul and they absorb everything you say and actually want to hear more. You share hopes for the future, dreams that will never come true, goals that we

In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
tokenizer=Tokenizer()

In [7]:
tokenizer.fit_on_texts([data])

In [8]:
##assigning labels for each words as machine works on number
tokenizer.word_index

{'you': 1,
 'to': 2,
 'and': 3,
 'the': 4,
 'a': 5,
 'i': 6,
 'love': 7,
 'is': 8,
 'in': 9,
 'of': 10,
 'it': 11,
 'that': 12,
 'your': 13,
 'not': 14,
 'for': 15,
 'be': 16,
 'but': 17,
 'are': 18,
 'they': 19,
 'or': 20,
 'can': 21,
 'have': 22,
 'will': 23,
 'we': 24,
 'all': 25,
 'with': 26,
 'never': 27,
 'when': 28,
 'so': 29,
 'my': 30,
 "don't": 31,
 'always': 32,
 'life': 33,
 'up': 34,
 'heart': 35,
 'at': 36,
 'he': 37,
 'who': 38,
 'because': 39,
 'if': 40,
 'me': 41,
 'as': 42,
 'there': 43,
 'make': 44,
 'just': 45,
 'this': 46,
 'than': 47,
 'only': 48,
 'them': 49,
 'soul': 50,
 'was': 51,
 'no': 52,
 'give': 53,
 'like': 54,
 'someone': 55,
 'do': 56,
 'what': 57,
 'about': 58,
 'think': 59,
 'world': 60,
 'want': 61,
 'her': 62,
 'too': 63,
 'she': 64,
 "it's": 65,
 'true': 66,
 'person': 67,
 'loved': 68,
 'how': 69,
 'our': 70,
 'best': 71,
 'on': 72,
 'things': 73,
 'something': 74,
 'one': 75,
 'way': 76,
 'ever': 77,
 'time': 78,
 'know': 79,
 'find': 80,
 'more

In [9]:
len(tokenizer.word_index)

1066

In [10]:
#creating the input output for the supervised model
input_seq=[]
for sentences in data.split('\n'):
  seq=tokenizer.texts_to_sequences([sentences])[0]

  for i in range(1,len(seq)):
    input_seq.append(seq[:i+1])


In [11]:
input_seq

[[143, 291],
 [143, 291, 435],
 [143, 291, 435, 3],
 [143, 291, 435, 3, 5],
 [143, 291, 435, 3, 5, 144],
 [143, 291, 435, 3, 5, 144, 436],
 [143, 291, 435, 3, 5, 144, 436, 6],
 [143, 291, 435, 3, 5, 144, 436, 6, 44],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124, 10],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124, 10, 292],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124, 10, 292, 3],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124, 10, 292, 3, 36],
 [143, 291, 435, 3, 5, 144, 436, 6, 44, 173, 6, 85, 124, 10, 292, 3, 36, 174],
 [143,
  291,
  435,
  3,
  5,
  144,
  436,
  6,
  44,
  173,
  6,
  85,
  124,
  10,
  292,
  3,
  36,
  174,
  216],
 [143,
  291,
  435,
  3,
  5,
  144,
  436,
  6,
  44,
  173,
  6,
  85,
  124,
  10,
  292,
  3,
  36,


In [12]:
##inorder to make array of equal lenmgth we do padding for it we require the max length of the sequence and rest will be padded with zero to make them all of equal length
max_len=max([len(x) for x in input_seq])
print(max_len)

450


In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_seq=pad_sequences(input_seq,maxlen=max_len,padding='pre')

In [14]:
padded_input_seq

array([[   0,    0,    0, ...,    0,  143,  291],
       [   0,    0,    0, ...,  143,  291,  435],
       [   0,    0,    0, ...,  291,  435,    3],
       ...,
       [   0,    0,    0, ..., 1065, 1066,    8],
       [   0,    0,    0, ..., 1066,    8,   29],
       [   0,    0,    0, ...,    8,   29,  150]], dtype=int32)

In [15]:
##x-vale
x=padded_input_seq[:,:-1]
x

array([[   0,    0,    0, ...,    0,    0,  143],
       [   0,    0,    0, ...,    0,  143,  291],
       [   0,    0,    0, ...,  143,  291,  435],
       ...,
       [   0,    0,    0, ...,   29, 1065, 1066],
       [   0,    0,    0, ..., 1065, 1066,    8],
       [   0,    0,    0, ..., 1066,    8,   29]], dtype=int32)

In [16]:
##Yvalue
y=padded_input_seq[:,-1]
y

array([291, 435,   3, ...,   8,  29, 150], dtype=int32)

In [17]:
##it is a multiclass classification task we will try to find the correct output
##by using softmax the one with highest probability will be the output for representation we will use one hot encoding
## example if output is 2 then [0,1,0,0,0.......]


x.shape

(4534, 449)

In [18]:
y.shape

(4534,)

In [19]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=1067)

In [20]:
y.shape

(4534, 1067)

In [21]:
###now modeling part
##embeding->lstm->dense->output

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [23]:
model=Sequential()
model.add(Embedding(1067,100,input_length=449))
model.add(LSTM(150))
model.add(Dense(1067,activation='softmax'))

In [24]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 449, 100)          106700    
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 1067)              161117    
                                                                 
Total params: 418417 (1.60 MB)
Trainable params: 418417 (1.60 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.fit(x,y,epochs=50)

Epoch 1/50
142/142 [==============================] - 26s 134ms/step - loss: 6.2184 - accuracy: 0.0335
Epoch 2/50
142/142 [==============================] - 12s 82ms/step - loss: 5.7877 - accuracy: 0.0439
Epoch 3/50
142/142 [==============================] - 8s 54ms/step - loss: 5.6795 - accuracy: 0.0441
Epoch 4/50
142/142 [==============================] - 5s 33ms/step - loss: 5.5952 - accuracy: 0.0518
Epoch 5/50
142/142 [==============================] - 4s 31ms/step - loss: 5.4924 - accuracy: 0.0596
Epoch 6/50
142/142 [==============================] - 6s 41ms/step - loss: 5.3733 - accuracy: 0.0710
Epoch 7/50
142/142 [==============================] - 3s 23ms/step - loss: 5.2322 - accuracy: 0.0854
Epoch 8/50
142/142 [==============================] - 3s 23ms/step - loss: 5.0662 - accuracy: 0.1065
Epoch 9/50
142/142 [==============================] - 6s 38ms/step - loss: 4.8835 - accuracy: 0.1292
Epoch 10/50
142/142 [==============================] - 3s 21ms/step - loss: 4.6874 - acc

In [37]:
import numpy as np


text="dance like"
for i in range(15):
  ##tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  ##padding
  padded_token_text=pad_sequences([token_text],maxlen=449,padding='pre')
  ##predict
  val=np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index==val:
      text=text + " " + word
      print(text)


1/1 [==============================] - 0s 23ms/step
dance like a
1/1 [==============================] - 0s 22ms/step
dance like a little
1/1 [==============================] - 0s 22ms/step
dance like a little weird
1/1 [==============================] - 0s 21ms/step
dance like a little weird and
1/1 [==============================] - 0s 20ms/step
dance like a little weird and life
1/1 [==============================] - 0s 22ms/step
dance like a little weird and life is
1/1 [==============================] - 0s 24ms/step
dance like a little weird and life is a
1/1 [==============================] - 0s 22ms/step
dance like a little weird and life is a little
1/1 [==============================] - 0s 22ms/step
dance like a little weird and life is a little weird
1/1 [==============================] - 0s 21ms/step
dance like a little weird and life is a little weird and
1/1 [==============================] - 0s 20ms/step
dance like a little weird and life is a little weird and when
1/1 [==